module.exports = {
  COMMUNITY_CHAT: 'COMMUNITY_CHAT',
  USER_CONNECTED: 'USER_CONNECTED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  TYPING: 'TYPING',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT',
  SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT',
  UPDATE_USER: 'UPDATE_USER',
  USER_UPDATED: 'USER_UPDATED',
};
